version: '3.9'
services:
  database:
    image: postgres:17
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: development-only-postgres-password
    volumes:
      - "pgdata:/var/lib/postgresql/data"
volumes:
  pgdata: {}