services:
  app:
    build: .
    volumes:
      - ".env.docker:/build/.env"
    ports:
      - "3000:3000"
  database:
    image: postgres:17
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: development-only-postgres-password
    volumes:
      - "pgdata:/var/lib/postgresql/data"
volumes:
  pgdata: {}